pod 'BRYDescriptionBuilder', git: 'https://github.com/segiddins/BRYDescriptionBuilder', branch: 'keypaths'
pod "SEGBlock", :path => "../SEGBlock.podspec"

#target "SEGBlock" do
#end

target "SEGBlockTests" do
  pod "Expecta"
end

